import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import "./globals.css";

import { getContacts } from "./_data";
import { createContact } from "./actions";
import { SideNav } from "./side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout(props: PropsWithChildren) {
  const q = "";
  const searching = false;
  const contacts = await getContacts();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="sidebar">
          <h1>Remix Contacts</h1>
          <div>
            <form id="search-form" role="search">
              <input
                id="q"
                aria-label="Search contacts"
                className={searching ? "loading" : ""}
                placeholder="Search"
                type="search"
                name="q"
                defaultValue={q || ""}
              />
              <div id="search-spinner" aria-hidden hidden={!searching} />
            </form>
            <form action={createContact}>
              <button type="submit">New</button>
            </form>
          </div>

          <SideNav contacts={contacts} />
        </div>

        {/* navigation.state === "loading" && !searching ? "loading" : "" */}
        <div className={""} id="detail">
          {props.children}
        </div>
      </body>
    </html>
  );
}
